name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Cap pip version
      run: pip install -U "pip<23"
    - name: Install build dependencies
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  documentation:
    name: Version doc with Mike
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: Cap pip version
      run: pip install -U "pip<23"
    - name: Install dependencies
      run: pip install .[doc]
    - name: Set up Git
      run: |
        git config user.name ${{ github.actor }}
        git config user.email ${{ github.actor }}@users.noreply.github.com
    - name: Build documentation
      run: |
        git fetch origin gh-pages
        mike deploy --push --no-redirect --update-aliases $GITHUB_REF_NAME latest
